// <auto-generated />
using System;
using FleetExecutive.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FleetExecutive.Infrastructure.Persistence.Migrations.Tenant
{
    [DbContext(typeof(FleetExecutiveDbContext))]
    partial class FleetExecutiveDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FleetExecutive.Domain.Clientes.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AtendenteId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CpfCnpj")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("_tags")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.HasKey("Id");

                    b.HasIndex("CpfCnpj");

                    b.HasIndex("Email");

                    b.HasIndex("Nome");

                    b.HasIndex("Tipo");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Domain.Clientes.CustomerAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cep")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Numero")
                        .HasColumnType("text");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Tipo");

                    b.ToTable("customer_addresses", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Domain.Financeiro.Charge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ImpostoRetido")
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Origem")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PagoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateOnly>("VenceEm")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("Origem");

                    b.HasIndex("Status");

                    b.HasIndex("Tipo");

                    b.ToTable("charges", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Domain.Financeiro.Commission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Alterada")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("JustificativaAlteracao")
                        .HasColumnType("text");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PagoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Percentual")
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("RecebedorId")
                        .HasColumnType("uuid");

                    b.Property<int>("RecebedorTipo")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("Status");

                    b.HasIndex("Tipo");

                    b.HasIndex("RecebedorTipo", "RecebedorId");

                    b.ToTable("commissions", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Domain.Financeiro.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("GeradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Domain.Orcamentos.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AtendenteId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DataServico")
                        .HasColumnType("date");

                    b.Property<string>("MotivoPerda")
                        .HasColumnType("text");

                    b.Property<int>("Origem")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorEstimado")
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Origem");

                    b.HasIndex("Status");

                    b.ToTable("quotes", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Domain.Orcamentos.QuoteService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DataIda")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataVolta")
                        .HasColumnType("date");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<TimeOnly>("HoraIda")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("HoraVolta")
                        .HasColumnType("time without time zone");

                    b.Property<string>("IdiomaRequerido")
                        .HasColumnType("text");

                    b.Property<int>("NumPassageiros")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid");

                    b.Property<int>("Subtipo")
                        .HasColumnType("integer");

                    b.Property<int>("TipoServico")
                        .HasColumnType("integer");

                    b.Property<int?>("TipoVeiculoPreferido")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("_caracteristicas")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("caracteristicas");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.HasIndex("Subtipo");

                    b.HasIndex("TipoServico");

                    b.HasIndex("TipoVeiculoPreferido");

                    b.ToTable("quote_services", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Domain.Pedidos.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AceiteEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AtendenteId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoAceiteTermos")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("FormaPagamento")
                        .HasColumnType("text");

                    b.Property<string>("MotivoCancelamento")
                        .HasColumnType("text");

                    b.Property<int>("Origem")
                        .HasColumnType("integer");

                    b.Property<Guid?>("QuoteId")
                        .HasColumnType("uuid");

                    b.Property<int>("StatusComercial")
                        .HasColumnType("integer");

                    b.Property<int>("StatusOperacional")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Origem");

                    b.HasIndex("QuoteId")
                        .IsUnique();

                    b.HasIndex("StatusComercial");

                    b.HasIndex("StatusOperacional");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Domain.Pedidos.OrderAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AutorId")
                        .HasColumnType("uuid");

                    b.Property<string>("CampoAlterado")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Justificativa")
                        .HasColumnType("text");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("text");

                    b.Property<string>("ValorNovo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("order_audit_logs", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Domain.Pedidos.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Acrescimo")
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("ChaveAcessoCheckin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("CheckinEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("CheckinLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("CheckinLng")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DataHoraIda")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DataHoraVolta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("FimServicoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("InicioServicoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("LocalizacaoAtualLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("LocalizacaoAtualLng")
                        .HasColumnType("double precision");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorServico")
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChaveAcessoCheckin")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.HasIndex("Tipo");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Domain.Prestadores.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ComissaoPercentual")
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("FonteIndicacao")
                        .HasColumnType("text");

                    b.Property<bool>("Indicacao")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Referencia")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("_capacidades")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("capacidades");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.HasIndex("Referencia");

                    b.HasIndex("Tipo");

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Domain.Prestadores.DriverDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<string>("Numero")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ValidoAte")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("Tipo");

                    b.ToTable("driver_documents", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Domain.Prestadores.DriverLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("Nivel");

                    b.ToTable("driver_languages", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Domain.Tarefas.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Prazo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Prioridade")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ResponsavelId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VinculoId")
                        .HasColumnType("uuid");

                    b.Property<int?>("VinculoTipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Prioridade");

                    b.HasIndex("ResponsavelId");

                    b.HasIndex("Status");

                    b.HasIndex("VinculoTipo", "VinculoId");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Domain.Usuarios.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UsadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Domain.Usuarios.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("UltimoLoginEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Perfil");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Domain.Usuarios.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique();

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Domain.Veiculos.Fleet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("Capacidade")
                        .HasColumnType("integer");

                    b.Property<int>("Categoria")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<Guid?>("GaragemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TemAntt")
                        .HasColumnType("boolean");

                    b.Property<bool>("TemAr")
                        .HasColumnType("boolean");

                    b.Property<bool>("TemWc")
                        .HasColumnType("boolean");

                    b.Property<bool>("TemWifi")
                        .HasColumnType("boolean");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("Tipo");

                    b.ToTable("fleets", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Domain.Veiculos.Garage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("garages", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Domain.Veiculos.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DisponivelDesde")
                        .HasColumnType("date");

                    b.Property<Guid>("FleetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GaragemId")
                        .HasColumnType("uuid");

                    b.Property<double?>("LocalizacaoLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("LocalizacaoLng")
                        .HasColumnType("double precision");

                    b.Property<string>("MotivoIndisponibilidade")
                        .HasColumnType("text");

                    b.Property<Guid?>("MotoristaHabitualId")
                        .HasColumnType("uuid");

                    b.Property<string>("NumeroOrdem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("_features")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("features");

                    b.HasKey("Id");

                    b.HasIndex("FleetId");

                    b.HasIndex("MotoristaHabitualId");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Infrastructure.Persistence.Lookups.CategoriaVeiculoLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("categoria_veiculo", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Infrastructure.Persistence.Lookups.NivelIdiomaLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("nivel_idioma", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Infrastructure.Persistence.Lookups.OrigemCobrancaLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("origem_cobranca", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Infrastructure.Persistence.Lookups.OrigemOrcamentoLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("origem_orcamento", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Infrastructure.Persistence.Lookups.PerfilLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("perfil", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Infrastructure.Persistence.Lookups.PrioridadeTarefaLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("prioridade_tarefa", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Infrastructure.Persistence.Lookups.StatusCobrancaLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("status_cobranca", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Infrastructure.Persistence.Lookups.StatusComercialLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("status_comercial", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Infrastructure.Persistence.Lookups.StatusComissaoLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("status_comissao", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Infrastructure.Persistence.Lookups.StatusFaturaLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("status_fatura", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Infrastructure.Persistence.Lookups.StatusFunilLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("status_funil", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Infrastructure.Persistence.Lookups.StatusOperacionalLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("status_operacional", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Infrastructure.Persistence.Lookups.StatusTarefaLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("status_tarefa", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Infrastructure.Persistence.Lookups.StatusVeiculoLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("status_veiculo", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Infrastructure.Persistence.Lookups.SubtipoServicoLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("subtipo_servico", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Infrastructure.Persistence.Lookups.TipoCobrancaLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("tipo_cobranca", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Infrastructure.Persistence.Lookups.TipoComissaoLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("tipo_comissao", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Infrastructure.Persistence.Lookups.TipoDocumentoPrestadorLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("tipo_documento_prestador", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Infrastructure.Persistence.Lookups.TipoEnderecoLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("tipo_endereco", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Infrastructure.Persistence.Lookups.TipoPessoaLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("tipo_pessoa", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Infrastructure.Persistence.Lookups.TipoPrestadorLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("tipo_prestador", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Infrastructure.Persistence.Lookups.TipoRecebedorComissaoLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("tipo_recebedor_comissao", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Infrastructure.Persistence.Lookups.TipoServicoLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("tipo_servico", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Infrastructure.Persistence.Lookups.TipoVeiculoLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("tipo_veiculo", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Infrastructure.Persistence.Lookups.VinculoTarefaLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("vinculo_tarefa", (string)null);
                });

            modelBuilder.Entity("FleetExecutive.Domain.Clientes.Customer", b =>
                {
                    b.HasOne("FleetExecutive.Infrastructure.Persistence.Lookups.TipoPessoaLookup", null)
                        .WithMany()
                        .HasForeignKey("Tipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetExecutive.Domain.Clientes.CustomerAddress", b =>
                {
                    b.HasOne("FleetExecutive.Domain.Clientes.Customer", null)
                        .WithMany("Enderecos")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetExecutive.Infrastructure.Persistence.Lookups.TipoEnderecoLookup", null)
                        .WithMany()
                        .HasForeignKey("Tipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetExecutive.Domain.Financeiro.Charge", b =>
                {
                    b.HasOne("FleetExecutive.Infrastructure.Persistence.Lookups.OrigemCobrancaLookup", null)
                        .WithMany()
                        .HasForeignKey("Origem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetExecutive.Infrastructure.Persistence.Lookups.StatusCobrancaLookup", null)
                        .WithMany()
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetExecutive.Infrastructure.Persistence.Lookups.TipoCobrancaLookup", null)
                        .WithMany()
                        .HasForeignKey("Tipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetExecutive.Domain.Financeiro.Commission", b =>
                {
                    b.HasOne("FleetExecutive.Infrastructure.Persistence.Lookups.TipoRecebedorComissaoLookup", null)
                        .WithMany()
                        .HasForeignKey("RecebedorTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetExecutive.Infrastructure.Persistence.Lookups.StatusComissaoLookup", null)
                        .WithMany()
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetExecutive.Infrastructure.Persistence.Lookups.TipoComissaoLookup", null)
                        .WithMany()
                        .HasForeignKey("Tipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetExecutive.Domain.Financeiro.Invoice", b =>
                {
                    b.HasOne("FleetExecutive.Infrastructure.Persistence.Lookups.StatusFaturaLookup", null)
                        .WithMany()
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetExecutive.Domain.Orcamentos.Quote", b =>
                {
                    b.HasOne("FleetExecutive.Infrastructure.Persistence.Lookups.OrigemOrcamentoLookup", null)
                        .WithMany()
                        .HasForeignKey("Origem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetExecutive.Infrastructure.Persistence.Lookups.StatusFunilLookup", null)
                        .WithMany()
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetExecutive.Domain.Orcamentos.QuoteService", b =>
                {
                    b.HasOne("FleetExecutive.Domain.Orcamentos.Quote", null)
                        .WithMany("Servicos")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetExecutive.Infrastructure.Persistence.Lookups.SubtipoServicoLookup", null)
                        .WithMany()
                        .HasForeignKey("Subtipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetExecutive.Infrastructure.Persistence.Lookups.TipoServicoLookup", null)
                        .WithMany()
                        .HasForeignKey("TipoServico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetExecutive.Infrastructure.Persistence.Lookups.TipoVeiculoLookup", null)
                        .WithMany()
                        .HasForeignKey("TipoVeiculoPreferido");
                });

            modelBuilder.Entity("FleetExecutive.Domain.Pedidos.Order", b =>
                {
                    b.HasOne("FleetExecutive.Infrastructure.Persistence.Lookups.OrigemOrcamentoLookup", null)
                        .WithMany()
                        .HasForeignKey("Origem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetExecutive.Infrastructure.Persistence.Lookups.StatusComercialLookup", null)
                        .WithMany()
                        .HasForeignKey("StatusComercial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetExecutive.Infrastructure.Persistence.Lookups.StatusOperacionalLookup", null)
                        .WithMany()
                        .HasForeignKey("StatusOperacional")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetExecutive.Domain.Pedidos.OrderItem", b =>
                {
                    b.HasOne("FleetExecutive.Domain.Pedidos.Order", null)
                        .WithMany("Itens")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetExecutive.Infrastructure.Persistence.Lookups.SubtipoServicoLookup", null)
                        .WithMany()
                        .HasForeignKey("Tipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetExecutive.Domain.Prestadores.Driver", b =>
                {
                    b.HasOne("FleetExecutive.Infrastructure.Persistence.Lookups.TipoPrestadorLookup", null)
                        .WithMany()
                        .HasForeignKey("Tipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetExecutive.Domain.Prestadores.DriverDocument", b =>
                {
                    b.HasOne("FleetExecutive.Domain.Prestadores.Driver", null)
                        .WithMany("Documentos")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetExecutive.Infrastructure.Persistence.Lookups.TipoDocumentoPrestadorLookup", null)
                        .WithMany()
                        .HasForeignKey("Tipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetExecutive.Domain.Prestadores.DriverLanguage", b =>
                {
                    b.HasOne("FleetExecutive.Domain.Prestadores.Driver", null)
                        .WithMany("Idiomas")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetExecutive.Infrastructure.Persistence.Lookups.NivelIdiomaLookup", null)
                        .WithMany()
                        .HasForeignKey("Nivel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetExecutive.Domain.Tarefas.TaskItem", b =>
                {
                    b.HasOne("FleetExecutive.Infrastructure.Persistence.Lookups.PrioridadeTarefaLookup", null)
                        .WithMany()
                        .HasForeignKey("Prioridade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetExecutive.Infrastructure.Persistence.Lookups.StatusTarefaLookup", null)
                        .WithMany()
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetExecutive.Infrastructure.Persistence.Lookups.VinculoTarefaLookup", null)
                        .WithMany()
                        .HasForeignKey("VinculoTipo");
                });

            modelBuilder.Entity("FleetExecutive.Domain.Usuarios.User", b =>
                {
                    b.HasOne("FleetExecutive.Infrastructure.Persistence.Lookups.PerfilLookup", null)
                        .WithMany()
                        .HasForeignKey("Perfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetExecutive.Domain.Veiculos.Fleet", b =>
                {
                    b.HasOne("FleetExecutive.Infrastructure.Persistence.Lookups.CategoriaVeiculoLookup", null)
                        .WithMany()
                        .HasForeignKey("Categoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetExecutive.Infrastructure.Persistence.Lookups.TipoVeiculoLookup", null)
                        .WithMany()
                        .HasForeignKey("Tipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetExecutive.Domain.Veiculos.Vehicle", b =>
                {
                    b.HasOne("FleetExecutive.Domain.Veiculos.Fleet", null)
                        .WithMany()
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FleetExecutive.Domain.Prestadores.Driver", null)
                        .WithMany()
                        .HasForeignKey("MotoristaHabitualId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FleetExecutive.Infrastructure.Persistence.Lookups.StatusVeiculoLookup", null)
                        .WithMany()
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetExecutive.Domain.Clientes.Customer", b =>
                {
                    b.Navigation("Enderecos");
                });

            modelBuilder.Entity("FleetExecutive.Domain.Orcamentos.Quote", b =>
                {
                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("FleetExecutive.Domain.Pedidos.Order", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("FleetExecutive.Domain.Prestadores.Driver", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("Idiomas");
                });
#pragma warning restore 612, 618
        }
    }
}
